[workspace]
resolver = "2"
members = ["projects/*"]
default-members = [
    "projects/panduck-markdown",
]

[profile.release]
lto = true
opt-level = "s"

[workspace.metadata.release]
push = false
tag = false